learning_templates/basic_app/urls.py
from django.urls import path,re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    re_path(r'^other/$',views.other,name='other'),
    re_path(r'^relative/$',views.relative_url_templates,name='relative')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
import basic_app.urls
import basic_app.views


urlpatterns = [
    re_path(r'^$', basic_app.views.index,name='index'),
    path('admin/', admin.site.urls),
    re_path(r'^basic_app/',include(basic_app.urls))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {'text':'Hello World','number':100}
    return render(request,'basic_app/index.html',context=context)


def other(request):
    return render(request,'basic_app/other.html')

def relative_url_templates(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/basic.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url "index" %}">Brand</a></li>
                    <li><a class="navbar-link" href="{% url "admin:index" %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url "basic_app:other" %}">Other</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
                {% comment %} Anything outside of this will be inherited if you extend {% endcomment %}

            {% endblock  %}
        </div>
        <script src="" async defer></script>
    </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}

    {% block body_block %}
            <h1>Welcome to Index Inhertited</h1>
            <h1>{{text|cut:"World"}}</h1>
            <h1>{{number|add:"99"}}</h1>
            
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}

{% block body_block %}
        <h1>Welcome to Other Inhertited!</h1>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Relative URL</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Welcome to relative url template!!</h1>
        <a href="{% url 'basic_app:other' %}"> Go To Other Page</a>
        <script src="" async defer></script>
    </body>
</html>